DROP SCHEMA IF EXISTS MOVIES;
CREATE SCHEMA MOVIES;
USE MOVIES;

CREATE TABLE MOVIE_RATING(
RATER_ID int(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
BAD_MOMS int(3),
SUICIDE_SQUAD int(3),
SUPERMAN_VS_BATMAN int(3),
ZOOTOPIA int(3),
DEADPOOL int(3),
CAPTAIN_AMERICA_CIVIL_WAR int(3)
);


INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(5, NULL, 3, 5, NULL, 1);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(2, 2, 3, 3, 5, 5);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(NULL, 3, 3, 5, 5, 2);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(3, 4, 1, 4, 5, 4);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(3, 1, 1, 4, NULL, 5);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(NULL, NULL, NULL, NULL, 5, 5);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(5, 2, 2, 3, 2, 3);

INSERT INTO MOVIE_RATING
(BAD_MOMS, SUICIDE_SQUAD, SUPERMAN_VS_BATMAN, ZOOTOPIA, DEADPOOL, CAPTAIN_AMERICA_CIVIL_WAR)
values(NULL, 5, 5, 5, NULL,5);

select * from  MOVIE_RATING